# Welcome to Jekyll!

# Website settings
title: "Yann Zhao"
description: "Yann Zhao's blog,use Jekyll and github pages."
keywords: "Yann,Bahai,blog,Jekyll,github,android"
baseurl: "/"
url: "yann.space"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Yann'
  first_name: 'Zhao'
  last_name: 'QiYang'
  email: 'qiyang0114@gmail.com'
  facebook_username: ''
  github_username: 'YannZhao'
  avatar: 'static/img/landing/yann-zhao.jpg'
  desc: 'I am a Android Application Development Engineer at present,And I used to be a Android Source Development Engineer as I worked for a IDH(Independent Design House) company two years ago. All in all I work with Android for five years already. I think life is a process of learning, not only on the Knowledge and skills, but also the spiritual aspect. there tree things deep inside me: Faith, Lova, Hope. Faith is the source where confidence comes, and love is the instrument overcome difficulties and obstacles, live with hope, I would not hesitate go forward! '

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: yannzhao
  public_key: pTuWiBrSDNZo5BM4yWtW1CqqDwZyEhW5A9OoaRCtrx1VyzP4rVCybhZPll2KFeC8

# share
bshare:
  uuid: d644820f-7127-4d8e-b2b9-be95b3e8d886

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
